version: '3.4'

#Volume for mysql container
volumes:
  datafiles:

services:
  #Databse Service 
  database:
    platform: linux/x86_64
    image : mysql:8.0.22
    ports:
        - "3306:3306"
    volumes:
        - datafiles:/var/lib/mysql
        - "./setup.sql:/docker-entrypoint-initdb.d/1.sql"
    restart: always
    environment:
        MYSQL_ROOT_PASSWORD: RootPass++
        MYSQL_USER: newuser
        MYSQL_PASSWORD: pass@word1234
        MYSQL_DATABASE: qrpatrol

  #Api Service 
  webapplication1:
    image: ${DOCKER_REGISTRY-}backend
    build:
      context: .
      dockerfile: ./Dockerfile
    depends_on:
        - database
    ports:
        - "7268:443"
    restart: always
    environment:
        - DBHOST=database
        - ASPNETCORE_ENVIRONMENt=Development