version: '3.4'

services:
  database:
      image: mysql:latest
      restart: always
      environment:       
        MYSQL_DATABASE: authdb
        MYSQL_ROOT_PASSWORD: root
      volumes:            
          - "./API/setup.sql:/docker-entrypoint-initdb.d/1.sql"
  api:
    image: ${DOCKER_REGISTRY-}api
    build:
      context: .
      dockerfile: API/Dockerfile
    depends_on:
       - database
    ports:
     - "5268:8080"
     - "7268:8081"
    restart: always
    environment:
      - DBHOST=database
      - ASPNETCORE_ENVIRONMENT=Development